### ISSUE TITLE
horizontal scrollbar on top and bottom of table? is there any way to add?

### ISSUE THREAD

**Issue by BinarySenseiii** [Julien-Marcou/Scrollable-Component#7]
![image](https://github.com/Julien-Marcou/Scrollable-Component/assets/68985954/39bc96e4-5bd6-4619-b610-e34896647ffd)

**Comment by Julien-Marcou** [comment]
For your information, this feature has now been implemented in the v2.0.0:

https://github.com/Julien-Marcou/Scrollable-Component/releases/tag/v2.0.0
